## Basic things

title:            Aleksandar Todorović (r3bl)
description:      Want to spend hours reading articles written by an aspiring writer/blogger/cotent creator? Heck yeah, you're in the right place! I write about open source software / hacking / cybersecurity / artificial intelligence.
disqus_shortname: r3bl
reading_time:     true
words_per_minute: 200
logo:             images/something.png
float_share:      false
url:              https://blog.r3bl.me

## Fixed top menu content

menu:
  - title: 'Home'
    url: 'https://blog.r3bl.me'
  - title: 'About'
    url: 'https://blog.r3bl.me/about'
  - title: 'Archive'
    url: 'https://blog.r3bl.me/en'
  - title: 'Website <i class="fa fa-external-link"></i>'
    url: 'https://r3bl.me/'
  - title: 'Bosanski'
    url: 'https://blog.r3bl.me/bs'


menu-bs:
  - title: 'Početna'
    url: 'https://blog.r3bl.me'
  - title: 'O meni'
    url: 'https://blog.r3bl.me/about'
  - title: 'Arhiva'
    url: 'https://blog.r3bl.me/bs'
  - title: 'Sajt'
    url: 'https://bs.r3bl.me/'
  - title: 'English'
    url: 'https://blog.r3bl.me/en'

## Info about the owner

owner:
  name:           Aleksandar Todorović
  site:           https://r3bl.me
  avatar:         images/avatar.jpg
  bio:            "Hacker. Open Source advocate. OCCRP Tech Associate. Opensource.com Community Moderator."
  email:          aleksandar.todorovic@mail.ru

## Social networking thingys

  twitter:      r3bl_
  facebook:     aleksandar.todorovic.r3bl
  github:       aleksandar-todorovic
  google_plus:  +AleksandarTodorovićr3bl

# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Sarajevo
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
